# Form implementation generated from reading ui file 'd:\Code\GUI\test\MiniCounter\Counter.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 500)
        Form.setStyleSheet("")
        self.NavigationBar = NavigationBar(parent=Form)
        self.NavigationBar.setGeometry(QtCore.QRect(0, 0, 70, 500))
        self.NavigationBar.setObjectName("NavigationBar")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=Form)
        self.stackedWidget.setGeometry(QtCore.QRect(73, 50, 527, 450))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.CardWidget = CardWidget(parent=self.page)
        self.CardWidget.setGeometry(QtCore.QRect(30, 20, 461, 231))
        palette = QtGui.QPalette()
        self.CardWidget.setPalette(palette)
        self.CardWidget.setStyleSheet("")
        self.CardWidget.setObjectName("CardWidget")
        self.layoutWidget = QtWidgets.QWidget(parent=self.CardWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 441, 211))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.TitleLabel = TitleLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.TitleLabel.setFont(font)
        self.TitleLabel.setObjectName("TitleLabel")
        self.horizontalLayout.addWidget(self.TitleLabel)
        self.CardWidget_2 = CardWidget(parent=self.layoutWidget)
        self.CardWidget_2.setObjectName("CardWidget_2")
        self.lbl_count = SubtitleLabel(parent=self.CardWidget_2)
        self.lbl_count.setGeometry(QtCore.QRect(34, 17, 301, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_count.sizePolicy().hasHeightForWidth())
        self.lbl_count.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_count.setFont(font)
        self.lbl_count.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_count.setObjectName("lbl_count")
        self.horizontalLayout.addWidget(self.CardWidget_2)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.TitleLabel_2 = TitleLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.TitleLabel_2.setFont(font)
        self.TitleLabel_2.setObjectName("TitleLabel_2")
        self.horizontalLayout_2.addWidget(self.TitleLabel_2)
        self.CardWidget_3 = CardWidget(parent=self.layoutWidget)
        self.CardWidget_3.setObjectName("CardWidget_3")
        self.edit_desc = LineEdit(parent=self.CardWidget_3)
        self.edit_desc.setGeometry(QtCore.QRect(-10, 17, 391, 33))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_desc.sizePolicy().hasHeightForWidth())
        self.edit_desc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.edit_desc.setFont(font)
        self.edit_desc.setStyleSheet("LineEdit, TextEdit, PlainTextEdit {\n"
"    color: black;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px solid rgba(0, 0, 0, 0);\n"
"    /* font: 14px \"Segoe UI\", \"Microsoft YaHei\"; */\n"
"    padding: 0px 10px;\n"
"    /* selection-background-color: #00a7b3;*/\n"
"}\n"
"\n"
"TextEdit,\n"
"PlainTextEdit {\n"
"    padding: 2px 3px 2px 8px;\n"
"}\n"
"\n"
"LineEdit:hover, TextEdit:hover, PlainTextEdit:hover {\n"
"    background-color: rgba(249, 249, 249, 0);\n"
"    border: 1px solid rgba(0, 0, 0, 0);\n"
"}\n"
"\n"
"LineEdit:focus {\n"
"    background-color: rgba(249, 249, 249, 0);\n"
"    border: 1px solid rgba(0, 0, 0, 0);\n"
"}\n"
"\n"
"TextEdit:focus,\n"
"PlainTextEdit:focus {\n"
"    background-color: rgba(249, 249, 249, 0);\n"
"    border: 1px solid rgba(0, 0, 0, 0);\n"
"}\n"
"\n"
"LineEdit:disabled, TextEdit:disabled,\n"
"PlainTextEdit:disabled {\n"
"    color: rgba(0, 0, 0, 0);\n"
"    background-color: rgba(249, 249, 249, 0);\n"
"}\n"
"\n"
"#lineEditButton {\n"
"    background-color: transparent;\n"
"    border-radius: 4px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"#lineEditButton:hover {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"}\n"
"\n"
"#lineEditButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"}\n"
"")
        self.edit_desc.setMaxLength(16)
        self.edit_desc.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.edit_desc.setProperty("transparent", False)
        self.edit_desc.setObjectName("edit_desc")
        self.horizontalLayout_2.addWidget(self.CardWidget_3)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_add = PushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.btn_add.setFont(font)
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout_3.addWidget(self.btn_add)
        self.btn_minus = PushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.btn_minus.setFont(font)
        self.btn_minus.setObjectName("btn_minus")
        self.horizontalLayout_3.addWidget(self.btn_minus)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.CardWidget_4 = CardWidget(parent=self.page)
        self.CardWidget_4.setGeometry(QtCore.QRect(30, 270, 461, 71))
        self.CardWidget_4.setObjectName("CardWidget_4")
        self.btn_pathselect = PushButton(parent=self.CardWidget_4)
        self.btn_pathselect.setGeometry(QtCore.QRect(386, 16, 61, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_pathselect.setFont(font)
        self.btn_pathselect.setObjectName("btn_pathselect")
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.CardWidget_4)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 381, 71))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setContentsMargins(15, 10, 0, 10)
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.SubtitleLabel_4 = SubtitleLabel(parent=self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.SubtitleLabel_4.setFont(font)
        self.SubtitleLabel_4.setObjectName("SubtitleLabel_4")
        self.verticalLayout_4.addWidget(self.SubtitleLabel_4)
        self.lbl_dirpath = BodyLabel(parent=self.layoutWidget1)
        self.lbl_dirpath.setProperty("lightColor", QtGui.QColor(107, 107, 107))
        self.lbl_dirpath.setObjectName("lbl_dirpath")
        self.verticalLayout_4.addWidget(self.lbl_dirpath)
        self.CardWidget_9 = CardWidget(parent=self.page)
        self.CardWidget_9.setGeometry(QtCore.QRect(30, 350, 461, 71))
        self.CardWidget_9.setObjectName("CardWidget_9")
        self.btn_filename = PushButton(parent=self.CardWidget_9)
        self.btn_filename.setGeometry(QtCore.QRect(386, 16, 61, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_filename.setFont(font)
        self.btn_filename.setObjectName("btn_filename")
        self.layoutWidget_4 = QtWidgets.QWidget(parent=self.CardWidget_9)
        self.layoutWidget_4.setGeometry(QtCore.QRect(0, 0, 381, 71))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_5.setContentsMargins(15, 10, 0, 10)
        self.verticalLayout_5.setSpacing(1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.SubtitleLabel_5 = SubtitleLabel(parent=self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.SubtitleLabel_5.setFont(font)
        self.SubtitleLabel_5.setObjectName("SubtitleLabel_5")
        self.verticalLayout_5.addWidget(self.SubtitleLabel_5)
        self.lbl_filename = BodyLabel(parent=self.layoutWidget_4)
        self.lbl_filename.setProperty("lightColor", QtGui.QColor(107, 107, 107))
        self.lbl_filename.setObjectName("lbl_filename")
        self.verticalLayout_5.addWidget(self.lbl_filename)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.TreeWidget = TreeWidget(parent=self.page_2)
        self.TreeWidget.setGeometry(QtCore.QRect(20, 20, 491, 411))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.TreeWidget.setFont(font)
        self.TreeWidget.setObjectName("TreeWidget")
        self.TreeWidget.headerItem().setTextAlignment(0, QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.TreeWidget.headerItem().setFont(0, font)
        self.TreeWidget.headerItem().setTextAlignment(1, QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.TreeWidget.headerItem().setFont(1, font)
        self.TreeWidget.headerItem().setTextAlignment(2, QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.TreeWidget.headerItem().setFont(2, font)
        self.TreeWidget.header().setDefaultSectionSize(140)
        self.stackedWidget.addWidget(self.page_2)
        self.HeaderCardWidget = HeaderCardWidget(parent=Form)
        self.HeaderCardWidget.setGeometry(QtCore.QRect(71, 0, 529, 500))
        self.HeaderCardWidget.setObjectName("HeaderCardWidget")
        self.NavigationBar.raise_()
        self.HeaderCardWidget.raise_()
        self.stackedWidget.raise_()

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Mini Counter"))
        self.TitleLabel.setText(_translate("Form", "计数"))
        self.lbl_count.setText(_translate("Form", "0"))
        self.TitleLabel_2.setText(_translate("Form", "描述"))
        self.btn_add.setText(_translate("Form", "添加"))
        self.btn_minus.setText(_translate("Form", "撤销"))
        self.btn_pathselect.setText(_translate("Form", "选择"))
        self.SubtitleLabel_4.setText(_translate("Form", "计数文件保存目录"))
        self.lbl_dirpath.setText(_translate("Form", "C:/ProgramData/MiniCounter"))
        self.btn_filename.setText(_translate("Form", "修改"))
        self.SubtitleLabel_5.setText(_translate("Form", "计数文件名"))
        self.lbl_filename.setText(_translate("Form", "Counter_1.cnt"))
        self.TreeWidget.headerItem().setText(0, _translate("Form", "计数"))
        self.TreeWidget.headerItem().setText(1, _translate("Form", "时间"))
        self.TreeWidget.headerItem().setText(2, _translate("Form", "描述"))
        self.HeaderCardWidget.setTitle(_translate("Form", "Mini Counter"))
from qfluentwidgets import BodyLabel, CardWidget, HeaderCardWidget, LineEdit, NavigationBar, PushButton, SubtitleLabel, TitleLabel, TreeWidget
